
[config]
skip_core_tasks = true


[tasks.release]
description = "Build release"
env = { RUSTFLAGS = "" }
command = "cargo"
args = ["build", "--target", "x86_64-pc-windows-msvc", "--release"]


[tasks.releasel]
description = "Build release"
env = { RUSTFLAGS = "" }
command = "cargo"
args = ["build", "--target", "x86_64-unknown-linux-gnu", "--release"]


[tasks.wasmrelease]
description = "Build release"
env = { RUSTFLAGS = "--cfg=web_sys_unstable_apis" }
command = "cargo"
args = [
    "build",
    "--no-default-features",
    "--target",
    "wasm32-unknown-unknown",
    "--release",
]


[tasks.wasmreleasen]
description = "Build --release nightly with bulk/shared memory"
env = { RUSTFLAGS = "--cfg=web_sys_unstable_apis -C target-feature=+atomics,+bulk-memory,+mutable-globals -Clink-args=--max-memory=4294967296" }
command = "cargo"
args = [
    "build",
    "--no-default-features",
    "--target",
    "wasm32-unknown-unknown",
    "-Z",
    "build-std=std,panic_abort",
    "--release",
]


[tasks.wasmdebugn]
description = "Build --debug nightly with bulk/shared memory"
env = { RUSTFLAGS = "--cfg=web_sys_unstable_apis -C target-feature=+atomics,+bulk-memory,+mutable-globals" }
command = "cargo"
args = [
    "build",
    "--no-default-features",
    "--target",
    "wasm32-unknown-unknown",
    "-Z",
    "build-std=std,panic_abort",
]


[tasks.rbindgen]
description = "Generate release wrapper"
command = "wasm-bindgen"
args = [
    "--out-dir",
    "dist",
    "--web",
    "./target/wasm32-unknown-unknown/release/dftvis.wasm",
]

[tasks.rbindgen_firefox]
description = "Generate release wrapper firefox"
command = "wasm-bindgen"
args = [
    "--out-dir",
    "dist",
    "--target",
    "no-modules",
    "--out-name",
    "dftvis_firefox",
    "./target/wasm32-unknown-unknown/release/dftvis.wasm",
]

[tasks.dbindgen]
description = "Generate debug wrapper"
command = "wasm-bindgen"
args = [
    "--out-dir",
    "dist",
    "--target",
    "web",
    "./target/wasm32-unknown-unknown/debug/dftvis.wasm",
]
[tasks.fix_text_enc_dec]
description = "Fixes bindgen's new TextDecoder('utf-8', ...) in AudioWorklet"
command = "bash"
args = ["fix_text_enc_dec.sh"]


# [tasks.rpack]
# description = "pack wasm release"
# command = "wasm-pack"
# args = ["build", "--target", "web", "--", "-Z", "build-std=panic_abort,std"]


[tasks.optwasm]
description = "Optimize WASM with wasm-opt"
command = "./bin/binaryen/bin/wasm-opt"
args = ["-O3", "dist/dftvis_bg.wasm", "-o", "dist/dftvis_bg.wasm"]

[tasks.optjs]
description = "Optimize release JS with terser"
command = "npx"
args = ["terser", "-c", "-m", "-o", "dist/dftvis.js", "dist/dftvis.js"]

[tasks.rb]
description = "Combine the build and serve tasks"
workspace = false
#dependencies = ["wasmreleasen", "rbindgen", "optwasm", "optjs"]
dependencies = [
    "wasmreleasen",
    "rbindgen",
    "rbindgen_firefox",
    "fix_text_enc_dec",
]

[tasks.rbo]
description = "Combine the build and serve tasks"
workspace = false
dependencies = ["rb", "optjs", "optwasm"]

[tasks.db]
description = "Combine the build and serve tasks"
workspace = false
#dependencies = ["wasmdebugn", "dbindgen", "optwasm", "optjs"]
dependencies = ["wasmdebugn", "dbindgen"]


# [tasks.rp]
# description = "Combine the build and serve tasks"
# workspace = false
# dependencies = ["wasmreleasen", "rpack"]
